version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.15.5

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}

  eslint:
    docker:
      - image: circleci/node:14.15.5

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}

      - run:
          name: ESLint App
          command: npm run eslint

  test_app:
    docker:
      - image: circleci/node:14.15.5
      - image: circleci/postgres:11.9-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}

      - run:
          name: Test App
          command: NUKE_TEST_DB=1 npm run test:app -- --ci --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "artifacts/jest"
            JEST_JUNIT_OUTPUT_NAME: "results-app.xml"

      - store_test_results:
          path: artifacts

workflows:
  version: 2
  build-app:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/

      - eslint:
          requires:
            - build
          filters:
            branches:
              only: /.*/

      - test_app:
          requires:
            - build
          filters:
            branches:
              only: /.*/
